version: '3'

services:
  weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - WEATHER_API_KEY=BD9E7QBCGTLENYPBUEUGV6DKA
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: