definitions:
  services.WeatherResponse:
    properties:
      conditions:
        type: string
      location:
        type: string
      temperature:
        type: number
      time:
        type: string
    type: object
info:
  contact: {}
paths:
  /weather/{city}:
    get:
      description: Get the current weather information for a given city.
      parameters:
      - description: City name
        in: path
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.WeatherResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get weather information for a city
swagger: "2.0"
